<Project Sdk="Microsoft.NET.Sdk">
    <Import Condition="Exists('../GamePath.props')" Project="../GamePath.props"/>
    <PropertyGroup>
        <AssemblyName>TasTools</AssemblyName>
        <Description>TAS Tooling for Silksong based on CelesteStudio</Description>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Version>1.0.0</Version>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <PublishRelease>true</PublishRelease>
        <NoWarn>MSB3277</NoWarn>

        <!-- todo macOS -->
        <GamePath Condition="'$(OS)' == 'Windows_NT'">C:/Program Files (x86)/Steam/steamapps/common/Hollow Knight Silksong</GamePath>
        <GamePath Condition="'$(OS)' != 'Windows_NT'">$(HOME)/.local/share/Steam/steamapps/common/Hollow Knight Silksong</GamePath>
        <ManagedDir Condition="'$(ManagedDir)' == ''">$(GamePath)/Hollow Knight Silksong_Data/Managed</ManagedDir>

        <!-- If you're not using R2Modman/Thunderstore, this can be GamePath as well. Only used in CopyDir -->
        <ProfileDir Condition="'$(OS)' == 'Windows_NT'">$(AppData)/r2modmanPlus-local/HollowKnightSilksong/profiles/Default</ProfileDir>
        <ProfileDir Condition="'$(OS)' != 'Windows_NT'">$(HOME)/.config/r2modmanPlus-local/HollowKnightSilksong/profiles/Default</ProfileDir>
        <!-- After building, copy the dll to this folder. Useful for hot-reloading: https://github.com/BepInEx/BepInEx.Debug/blob/master/README.md#scriptengine -->
        <CopyDir Condition="'$(CopyDir)' == ''">$(ProfileDir)/BepInEx/plugins</CopyDir>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(ManagedDir)/Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Assembly-CSharp-firstpass">
            <HintPath>$(ManagedDir)/Assembly-CSharp-firstpass.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="PlayMaker">
            <HintPath>$(ManagedDir)/PlayMaker.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="TeamCherry.TK2D">
            <HintPath>$(ManagedDir)/TeamCherry.TK2D.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="PlayMaker">
            <HintPath>$(ManagedDir)/PlayMaker.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Unity.InputSystem" Condition="Exists('$(ManagedDir)/Unity.InputSystem.dll')">
            <HintPath>$(ManagedDir)/Unity.InputSystem.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <PropertyGroup Condition="Exists('$(ManagedDir)/Unity.InputSystem.dll')">
        <DefineConstants>$(DefineConstants);UNITY_NEW_INPUT_SYSTEM</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets/idle-normalization.json">
            <LogicalName>idle-normalization.json</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="Assets/scene-catalog.json">
            <LogicalName>scene-catalog.json</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" />
        <PackageReference Include="BepInEx.Core" Version="5.*" IncludeAssets="compile" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="UnityEngine.Modules" Version="6000.0.50" IncludeAssets="compile" />

        <ProjectReference Include="../StudioCommunication/StudioCommunication.csproj" />
        <ProjectReference Include="../../DevUtils/DevUtils.csproj" Private="false" />
    </ItemGroup>

    <Target Name="CheckReferences" BeforeTargets="BeforeBuild">
        <ItemGroup>
            <MissingReferences Include="@(Reference)" Condition="!Exists('%(Reference.HintPath)')" />
        </ItemGroup>
        <Error Condition="@(MissingReferences->Count()) > 0" Text="Missing reference(s);
@(MissingReferences->'%(HintPath)', ',&#x0A;')
Did you forget to adjust your GamePath '$(ManagedDir)'?" />
    </Target>

    <Target Name="CopyMod" AfterTargets="PostBuildEvent" Condition="'$(CopyDir)' != ''">
        <Message Importance="high" Text="copying $(TargetPath) to $(CopyDir) ..." />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(CopyDir)" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(CopyDir)" SkipUnchangedFiles="true" />

        <!--        <Copy SourceFiles="$(TargetDir)StudioCommunication.dll" DestinationFolder="$(CopyDir)/../Plugins/" SkipUnchangedFiles="true" />-->
    </Target>

    <Target Name="PackageMod" AfterTargets="Publish">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="../thunderstore/build/dll" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)publish/MemoryPack.Core.dll" DestinationFolder="../thunderstore/build/dll" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)publish/StudioCommunication.dll" DestinationFolder="../thunderstore/build/dll" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)publish/System.Collections.Immutable.dll" DestinationFolder="../thunderstore/build/dll" SkipUnchangedFiles="true" />
        <!-- <Exec Command="tcli build - -config-path ../thunderstore/thunderstore.toml" /> TODO--> 
    </Target>
</Project>