name: NetFramework.Legacy.CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths-ignore:
      - LICENSE
      - README.md
      - 'Docs/*.md'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-2022
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]') && !startsWith(github.ref, 'refs/tags/')"

    env:
      Solution_Name: CelesteTAS-EverestInterop.sln

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: Build with MSBuild
        run: msbuild $env:Solution_Name -t:build -restore -p:Configuration=Release,RestoreLockedMode=true -m

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CelesteTAS
          path: CelesteTAS-EverestInterop/bin/net452
